import type { Scenario } from '../core/building';

/** Two-storey family home with a kitchen fire. Trucks arrive over the first turns. */
export const houseFire: Scenario = {
  name: 'Kitchen Fire — Two-Storey House',
  description:
    'A stove fire has spread into the kitchen cabinets. Three residents are still inside. ' +
    'Park your trucks, get the residents out and put the fire out before it climbs the stairwell.',
  seed: 20261001,
  preburn: 3,
  floors: [
    {
      // Ground floor: house, yards, sidewalks, road and hydrants.
      plan: [
        '..........................',
        '..........................',
        '....##W#####W#W#####W#.::.',
        '....#,,,,,,,w_Swttttt#.::.',
        '....#,,,,,,,w_Swttttt#.::.',
        '....W,,,,,,,D__Dttttt#.::.',
        '....#,,,,,,,w__wttttt#.::.',
        '....#wwwwDwww__wwwDww#.::.',
        '....#,,,,,,,w__wttttt#.::.',
        '....W,,,,,,,w__wttttt#.::.',
        '....#,,,,,,,w__wttttt#.::.',
        '....#########DD#######.::.',
        '.............--........::.',
        '.............--........::.',
        '-----------------------::-',
        '==========================',
        '==========================',
        '--------------------------',
      ],
      contents: [
        '  T       T         T     ',
        '                          ',
        '                          ',
        '     ss         ccocc     ',
        '     s  k           k     ',
        '                   kk     ',
        '     h     p        c     ',
        '                          ',
        '     hh                   ',
        '        k           c     ',
        '     s     p       c      ',
        '                          ',
        '   p   p         p  p     ',
        '                          ',
        '      H                   ',
        '                          ',
        '                          ',
        '                    H     ',
      ],
    },
    {
      // Upper floor
      plan: [
        '                          ',
        '                          ',
        '    ##W#####W#W#####W#    ',
        '    #,,,,,,,w_Sw,,,,,#    ',
        '    #,,,,,,,w_Sw,,,,,#    ',
        '    W,,,,,,,D__D,,,,,W    ',
        '    #,,,,,,,w__w,,,,,#    ',
        '    #wwwwDwww__wwwDww#    ',
        '    #tttttttw__w,,,,,#    ',
        '    Wtttttttw__w,,,,,W    ',
        '    #tttttttw__w,,,,,#    ',
        '    ####W########W####    ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
      ],
      contents: [
        '                          ',
        '                          ',
        '                          ',
        '     bb          bb       ',
        '     bb          bb       ',
        '                          ',
        '           h        h     ',
        '                          ',
        '     c                    ',
        '                   p      ',
        '                bb  h     ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
      ],
    },
  ],
  fires: [
    { pos: { floor: 0, x: 18, y: 3 }, intensity: 2 },
    { pos: { floor: 0, x: 19, y: 3 }, intensity: 1 },
  ],
  civilians: [
    { name: 'Maria', pos: { floor: 1, x: 6, y: 4 } },
    { name: 'Theo', pos: { floor: 1, x: 18, y: 9 } },
    { name: 'Grandpa Joe', pos: { floor: 0, x: 7, y: 9 } },
  ],
  dispatch: [
    { name: 'Engine 1', type: 'engine', arrivalTurn: 1, crew: ['Alvarez', 'Brooks', 'Chen'] },
    { name: 'Ladder 7', type: 'ladder', arrivalTurn: 3, crew: ['Diaz', 'Evans'] },
    { name: 'Engine 4', type: 'engine', arrivalTurn: 5, crew: ['Foster', 'Garcia', 'Hill'] },
  ],
};

export const SCENARIOS: Scenario[] = [houseFire];
