import type { Scenario } from '../core/building';

/** Two-storey family home; the fire starts somewhere likely, different each game. Trucks arrive over the first turns. */
export const houseFire: Scenario = {
  name: 'House Fire — Two-Storey House',
  description:
    'Smoke is showing from a two-storey house. Neighbours say three residents are still inside — nobody knows ' +
    'where, or where the fire started. The front door is locked. Size it up from the outside: watch where smoke ' +
    'and fire show at the windows, find the fire and the residents, and put it out.',
  seed: 20261001,
  preburn: 3,
  floors: [
    {
      // Ground floor: house, yards, sidewalks, road and hydrants. Kitchen and living room open onto the hall.
      plan: [
        '..........................',
        '..........................',
        '....##W#####W#W#####W#.::.',
        '....#,,,,,,,w_Swttttt#.::.',
        '....#,,,,,,,w_Swttttt#.::.',
        '....W,,,,,,,d__dttttt#.::.',
        '....#,,,,,,,w__wttttt#.::.',
        '....#wwwwDwww__wwwDww#.::.',
        '....#,,,,,,,w__wttttt#.::.',
        '....W,,,,,,,w__wttttt#.::.',
        '....#,,,,,,,w__wttttt#.::.',
        '....#########LL#######.::.',
        '.............--........::.',
        '.............--........::.',
        '-----------------------::-',
        '==========================',
        '==========================',
        '==========================',
        '==========================',
        '--------------------------',
      ],
      contents: [
        '  T       T         T     ',
        '                          ',
        '                          ',
        '     ss         ccocc     ',
        '     s  k           k     ',
        '                   kk     ',
        '     h     p        c     ',
        '                          ',
        '     hh                   ',
        '        k           c     ',
        '     s     p       c      ',
        '                          ',
        '   p   p         p  p     ',
        '                          ',
        '      H                   ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                    H     ',
      ],
    },
    {
      // Upper floor: Maria's bedroom door (west) is open; Theo's rooms are behind closed doors.
      plan: [
        '                          ',
        '                          ',
        '    ##W#####W#W#####W#    ',
        '    #,,,,,,,w_Sw,,,,,#    ',
        '    #,,,,,,,w_Sw,,,,,#    ',
        '    W,,,,,,,d__D,,,,,W    ',
        '    #,,,,,,,w__w,,,,,#    ',
        '    #wwwwDwww__wwwDww#    ',
        '    #tttttttw__w,,,,,#    ',
        '    Wtttttttw__w,,,,,W    ',
        '    #tttttttw__w,,,,,#    ',
        '    ####W########W####    ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
      ],
      contents: [
        '                          ',
        '                          ',
        '                          ',
        '     bb          bb       ',
        '     bb          bb       ',
        '                          ',
        '           h        h     ',
        '                          ',
        '     c                    ',
        '                   p      ',
        '                bb  h     ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
      ],
    },
    {
      // Roof over the whole building
      plan: [
        '                          ',
        '                          ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '    RRRRRRRRRRRRRRRRRR    ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
        '                          ',
      ],
    },
  ],
  fires: [],
  randomOrigin: true,
  civilians: [
    { name: 'Maria', pos: { floor: 1, x: 6, y: 4 } },
    { name: 'Theo', pos: { floor: 1, x: 18, y: 9 } },
    { name: 'Grandpa Joe', pos: { floor: 0, x: 7, y: 9 } },
  ],
  dispatch: [
    { name: 'Engine 1', type: 'engine', arrivalTurn: 1, crew: ['Alvarez', 'Brooks', 'Chen'] },
    { name: 'Ladder 7', type: 'ladder', arrivalTurn: 3, crew: ['Diaz', 'Evans'] },
    { name: 'Engine 4', type: 'engine', arrivalTurn: 5, crew: ['Foster', 'Garcia', 'Hill'] },
  ],
};

export const SCENARIOS: Scenario[] = [houseFire];
